/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Ingredient, Recipe } from '../types.ts';

export const INITIAL_INGREDIENTS: Ingredient[] = [
  {
    id: 'ing_1',
    name: 'Leche Entera',
    category: 'generico',
    functionalGroup: 'lacteos',
    energy: 61,
    energyKJ: 255,
    carbs: 4.8,
    sugars: 4.8,
    totalSugars: 4.8,
    addedSugars: 0,
    proteins: 3.2,
    totalFats: 3.3,
    saturatedFats: 2.1,
    transFats: 0,
    fiber: 0,
    sodium: 44,
  },
  {
    id: 'ing_2',
    name: 'Crema de Leche',
    category: 'generico',
    energy: 292,
    energyKJ: 1222,
    carbs: 3.0,
    sugars: 3.0,
    totalSugars: 3.0,
    addedSugars: 0,
    proteins: 2.1,
    totalFats: 30.0,
    saturatedFats: 19.5,
    transFats: 0,
    fiber: 0,
    sodium: 30,
  },
  {
    id: 'ing_3',
    name: 'Azúcar Blanco',
    category: 'generico',
    functionalGroup: 'azucares',
    energy: 400,
    energyKJ: 1674,
    carbs: 100,
    sugars: 100,
    totalSugars: 100,
    addedSugars: 100,
    proteins: 0,
    totalFats: 0,
    saturatedFats: 0,
    transFats: 0,
    fiber: 0,
    sodium: 0,
  },
  {
    id: 'ing_4',
    name: 'Chocolate Amargo (60% Cacao)',
    brand: 'Fénix',
    category: 'especifico',
    functionalGroup: 'chocolates',
    energy: 546,
    energyKJ: 2285,
    carbs: 46,
    sugars: 40,
    totalSugars: 40,
    addedSugars: 40,
    proteins: 7.5,
    totalFats: 37,
    saturatedFats: 22,
    transFats: 0,
    fiber: 8,
    sodium: 15,
  },
  {
    id: 'ing_5',
    name: 'Leche en Polvo Descremada',
    category: 'generico',
    energy: 350,
    energyKJ: 1464,
    carbs: 52,
    sugars: 52,
    totalSugars: 52,
    addedSugars: 0,
    proteins: 35,
    totalFats: 0.8,
    saturatedFats: 0.5,
    transFats: 0,
    fiber: 0,
    sodium: 530,
  },
  {
    id: 'ing_6',
    name: 'Manteca de Cacao',
    category: 'generico',
    energy: 884,
    energyKJ: 3699,
    carbs: 0,
    sugars: 0,
    totalSugars: 0,
    addedSugars: 0,
    proteins: 0,
    totalFats: 100,
    saturatedFats: 60,
    transFats: 0,
    fiber: 0,
    sodium: 0,
  },
  {
    id: 'ing_7',
    name: 'Harina de Trigo 0000',
    category: 'generico',
    energy: 341,
    energyKJ: 1427,
    carbs: 70,
    sugars: 0,
    totalSugars: 0,
    addedSugars: 0,
    proteins: 10,
    totalFats: 1.2,
    saturatedFats: 0.3,
    transFats: 0,
    fiber: 3,
    sodium: 2,
  },
  {
    id: 'ing_8',
    name: 'Manteca',
    category: 'generico',
    energy: 717,
    energyKJ: 3000,
    carbs: 0.1,
    sugars: 0.1,
    totalSugars: 0.1,
    addedSugars: 0,
    proteins: 0.9,
    totalFats: 81,
    saturatedFats: 51,
    transFats: 3,
    fiber: 0,
    sodium: 11,
  },
  {
    id: 'ing_9',
    name: 'Huevo Entero',
    category: 'generico',
    energy: 155,
    energyKJ: 649,
    carbs: 1.1,
    sugars: 1.1,
    totalSugars: 1.1,
    addedSugars: 0,
    proteins: 13,
    totalFats: 11,
    saturatedFats: 3.3,
    transFats: 0,
    fiber: 0,
    sodium: 124,
  },
  {
    id: 'ing_10',
    name: 'Dulce de Leche Repostero',
    brand: 'Vacalin',
    category: 'especifico',
    energy: 300,
    energyKJ: 1255,
    carbs: 55,
    sugars: 50,
    totalSugars: 50,
    addedSugars: 40,
    proteins: 6,
    totalFats: 6,
    saturatedFats: 3.5,
    transFats: 0,
    fiber: 0,
    sodium: 120,
  },
  {
    id: 'ing_11',
    name: 'Aceite de Girasol',
    category: 'generico',
    energy: 884,
    energyKJ: 3699,
    carbs: 0,
    sugars: 0,
    totalSugars: 0,
    addedSugars: 0,
    proteins: 0,
    totalFats: 100,
    saturatedFats: 13,
    transFats: 0,
    fiber: 0,
    sodium: 0,
  },
  {
    id: 'ing_12',
    name: 'Sal Fina',
    category: 'generico',
    energy: 0,
    energyKJ: 0,
    carbs: 0,
    sugars: 0,
    totalSugars: 0,
    addedSugars: 0,
    proteins: 0,
    totalFats: 0,
    saturatedFats: 0,
    transFats: 0,
    fiber: 0,
    sodium: 38758,
  },
  {
    id: 'ing_13',
    name: 'Polvo de Hornear',
    category: 'generico',
    energy: 53,
    energyKJ: 222,
    carbs: 28,
    sugars: 0,
    totalSugars: 0,
    addedSugars: 0,
    proteins: 0,
    totalFats: 0,
    saturatedFats: 0,
    transFats: 0,
    fiber: 0,
    sodium: 10600,
  },
  {
    id: 'ing_14',
    name: 'Cacao en Polvo',
    category: 'generico',
    energy: 228,
    energyKJ: 954,
    carbs: 58,
    sugars: 2,
    totalSugars: 2,
    addedSugars: 0,
    proteins: 20,
    totalFats: 14,
    saturatedFats: 8,
    transFats: 0,
    fiber: 33,
    sodium: 21,
  },
  {
    id: 'ing_15',
    name: 'Lecitina de Soja',
    category: 'especifico',
    energy: 700,
    energyKJ: 2929,
    carbs: 8,
    sugars: 0,
    totalSugars: 0,
    addedSugars: 0,
    proteins: 0,
    totalFats: 70,
    saturatedFats: 12,
    transFats: 0,
    fiber: 0,
    sodium: 40,
  },
  {
    id: 'ing_16',
    name: 'Jarabe de Glucosa',
    category: 'generico',
    functionalGroup: 'azucares',
    energy: 310,
    energyKJ: 1297,
    carbs: 77,
    sugars: 20,
    totalSugars: 20,
    addedSugars: 20,
    proteins: 0,
    totalFats: 0,
    saturatedFats: 0,
    transFats: 0,
    fiber: 0,
    sodium: 20,
  },
  {
    id: 'ing_17',
    name: 'Goma Xántica',
    category: 'generico',
    functionalGroup: 'neutros',
    energy: 200,
    energyKJ: 837,
    carbs: 78,
    sugars: 0,
    totalSugars: 0,
    addedSugars: 0,
    proteins: 6,
    totalFats: 0,
    saturatedFats: 0,
    transFats: 0,
    fiber: 78,
    sodium: 3000,
  },
  {
    id: 'ing_18',
    name: 'Sorbato de Potasio',
    category: 'generico',
    energy: 0,
    energyKJ: 0,
    carbs: 0,
    sugars: 0,
    totalSugars: 0,
    addedSugars: 0,
    proteins: 0,
    totalFats: 0,
    saturatedFats: 0,
    transFats: 0,
    fiber: 0,
    sodium: 0,
  },
  {
    id: 'ing_19',
    name: 'Esencia de Vainilla',
    category: 'generico',
    energy: 288,
    energyKJ: 1205,
    carbs: 12,
    sugars: 12,
    totalSugars: 12,
    addedSugars: 12,
    proteins: 0,
    totalFats: 0,
    saturatedFats: 0,
    transFats: 0,
    fiber: 0,
    sodium: 9,
  },
  {
    id: 'ing_20',
    name: 'Clorofila (Colorante Natural)',
    category: 'generico',
    energy: 0,
    energyKJ: 0,
    carbs: 0,
    sugars: 0,
    totalSugars: 0,
    addedSugars: 0,
    proteins: 0,
    totalFats: 0,
    saturatedFats: 0,
    transFats: 0,
    fiber: 0,
    sodium: 0,
  },
  {
    id: 'ing_21',
    name: 'Glucosa en Polvo',
    category: 'generico',
    functionalGroup: 'azucares',
    energy: 380,
    energyKJ: 1590,
    carbs: 95,
    sugars: 30,
    totalSugars: 30,
    addedSugars: 30,
    proteins: 0,
    totalFats: 0,
    saturatedFats: 0,
    transFats: 0,
    fiber: 0,
    sodium: 20,
  }
];

export const INITIAL_RECIPE: Recipe = {
  id: 'recipe_1',
  name: 'Helado de Crema con Chocolate',
  type: 'final',
  ingredients: [
    { ingredientId: 'ing_1', amount: 500 }, // Leche
    { ingredientId: 'ing_2', amount: 250 }, // Crema
    { ingredientId: 'ing_3', amount: 180 }, // Azúcar
    { ingredientId: 'ing_5', amount: 40 },  // Leche polvo
    { ingredientId: 'ing_4', amount: 100 }, // Chips chocolate
  ],
  servingSize: 60, // 60g por porción
  servingMeasure: '1 bocha',
  totalYield: 1070, // Sum of ingredients
  finalYield: 1000, // Reduced by cooking/processing
  portionsPerPackage: 16,
  status: 'formulacion',
  estimatedDevTime: '1 semana',
};
